services:
  backend:
    build: 
      context: .
      dockerfile: tools/docker/Dockerfile.backend
    ports:
      - "3000:3000"
    volumes:
      - "./apps/backend:/usr/apps/backend"

  frontend:
    build: 
      context: .
      dockerfile: tools/docker/Dockerfile.frontend
    ports:
      - "5173:5173"
    volumes:
      - "./apps/frontend:/usr/apps/frontend"
      - "./libs/ui:/usr/libs/ui"
    depends_on:
      - backend

  storybook:
    build:
      context: .
      dockerfile: tools/docker/Dockerfile.storybook
    ports:
      - "6006:6006"
    volumes:
      - "./tools/storybook:/usr/tools/storybook"
      - "./libs/ui:/usr/libs/ui"