services:
  backend:
    build: 
      context: ./tools/docker
      dockerfile: Dockerfile.backend
    ports:
      - "3000:3000"
    volumes:
      - "./apps/backend:/usr/apps/src"

  frontend:
    build: 
      context: ./tools/docker
      dockerfile: Dockerfile.frontend
    ports:
      - "5173:5173"
    volumes:
      - "./apps/frontend:/usr/apps/frontend"
      - "./libs/ui:/usr/libs/ui"
    depends_on:
      - backend