FROM node:20

WORKDIR /usr/tools/storybook

RUN npm install -g pnpm

COPY tools/storybook/package.json tools/storybook/package-lock.json ./

RUN npm i

COPY tools/storybook ./

EXPOSE 6006

# Empêcher l'ouverture automatique du navigateur
CMD ["pnpm", "storybook", "--", "--no-open"]