# apps/frontend/Dockerfile
FROM node:20

WORKDIR /usr/apps/frontend

COPY apps/frontend/package.json apps/frontend/package-lock.json ./

RUN npm i

COPY apps/frontend ./

EXPOSE 5173

CMD ["npm", "run", "dev"]